# GitHub presets
safe: true
lsi: false

# custom settings
author: Matt Ross
author_email: matt@mattross.io
description: freeride sports
destination: ./_site
exclude:
  - package.json
  - Gruntfile.js
  - node_modules
  - README.md
gems:
  - jekyll-sitemap
keys:
  ga: false
name: FREERIDE SPORTS
permalink: pretty
source: .
timezone: America/New_York
url: http://www.freeridesports.com
host: "0.0.0.0"
