dev:
  image: jekyll/jekyll:pages
  command: jekyll serve --watch --incremental
  ports:
    - 4000:4000
  volumes:
    - .:/srv/jekyll

build:
  image: jekyll/jekyll:pages
  command: jekyll build
  volumes:
    - .:/srv/jekyll
